"""
MOSIP (Modular Open Source Identity Platform) Integration Module
Provides integration with MOSIP Pre-registration, Registration Client, and Android Registration Client
"""
import logging
import requests
from typing import Dict, Optional, List
from datetime import datetime

logger = logging.getLogger(__name__)


class MOSIPIntegration:
    """Integration with MOSIP modules for identity management"""
    
    def __init__(self, 
                 pre_registration_url: Optional[str] = None,
                 registration_client_url: Optional[str] = None,
                 api_key: Optional[str] = None):
        """
        Initialize MOSIP integration
        
        Args:
            pre_registration_url: Base URL for MOSIP Pre-registration service
            registration_client_url: Base URL for MOSIP Registration Client
            api_key: API key for authentication (if required)
        """
        self.pre_registration_url = pre_registration_url or "http://localhost:9090/preregistration/v1"
        self.registration_client_url = registration_client_url or "http://localhost:9091/registration-processor/v1"
        self.api_key = api_key
        self.headers = {
            "Content-Type": "application/json"
        }
        if api_key:
            self.headers["X-API-Key"] = api_key
    
    def submit_pre_registration(self, 
                                extracted_data: Dict[str, str],
                                document_images: List[bytes],
                                quality_scores: Dict[str, float]) -> Dict:
        """
        Submit extracted data to MOSIP Pre-registration service
        
        Args:
            extracted_data: Structured data extracted from OCR
            document_images: List of document images as bytes
            quality_scores: Quality metrics for the documents
        
        Returns:
            Response from MOSIP Pre-registration service
        """
        try:
            # Format data according to MOSIP Pre-registration API
            pre_reg_data = {
                "id": "mosip.pre-registration.document.upload",
                "version": "1.0",
                "requesttime": datetime.utcnow().isoformat(),
                "request": {
                    "preRegistrationId": None,  # Will be generated by MOSIP
                    "documents": [],
                    "demographicDetails": {
                        "name": extracted_data.get("name", ""),
                        "dateOfBirth": extracted_data.get("dob", ""),
                        "gender": extracted_data.get("gender", ""),
                        "address": {
                            "line1": extracted_data.get("address", ""),
                            "city": extracted_data.get("city", ""),
                            "state": extracted_data.get("state", ""),
                            "postalCode": extracted_data.get("pin_code", "")
                        },
                        "phone": extracted_data.get("phone", ""),
                        "email": extracted_data.get("email", "")
                    },
                    "qualityScores": {
                        "overall": quality_scores.get("quality", 0.0),
                        "blur": quality_scores.get("blur_score", 0.0),
                        "brightness": quality_scores.get("brightness", 0.0),
                        "contrast": quality_scores.get("contrast", 0.0)
                    }
                }
            }
            
            # Upload documents
            for idx, img_bytes in enumerate(document_images):
                # In real implementation, upload to MOSIP document service
                pre_reg_data["request"]["documents"].append({
                    "documentCategoryCode": "POA",  # Proof of Address
                    "documentTypeCode": "ID",
                    "fileFormat": "pdf",
                    "fileSize": len(img_bytes)
                })
            
            # Submit to MOSIP Pre-registration
            if self.pre_registration_url:
                response = requests.post(
                    f"{self.pre_registration_url}/applications",
                    json=pre_reg_data,
                    headers=self.headers,
                    timeout=30
                )
                if response.status_code == 200:
                    logger.info("Successfully submitted to MOSIP Pre-registration")
                    return response.json()
                else:
                    logger.warning(f"MOSIP Pre-registration returned status {response.status_code}")
                    return {"status": "error", "message": response.text}
            else:
                # Mock response for demo
                logger.info("MOSIP Pre-registration URL not configured, returning mock response")
                return {
                    "id": "mosip.pre-registration.document.upload",
                    "version": "1.0",
                    "responsetime": datetime.utcnow().isoformat(),
                    "response": {
                        "preRegistrationId": f"PRE-{datetime.now().strftime('%Y%m%d%H%M%S')}",
                        "status": "SUBMITTED",
                        "message": "Pre-registration submitted successfully (MOCK)"
                    }
                }
        
        except requests.exceptions.RequestException as e:
            logger.error(f"Error connecting to MOSIP Pre-registration: {e}")
            return {"status": "error", "message": str(e)}
        except Exception as e:
            logger.error(f"Error in MOSIP Pre-registration submission: {e}")
            return {"status": "error", "message": str(e)}
    
    def submit_registration(self,
                           pre_registration_id: str,
                           extracted_data: Dict[str, str],
                           biometric_data: Optional[Dict] = None) -> Dict:
        """
        Submit registration data to MOSIP Registration Client
        
        Args:
            pre_registration_id: Pre-registration ID from MOSIP
            extracted_data: Structured data extracted from OCR
            biometric_data: Optional biometric data (fingerprints, iris, face)
        
        Returns:
            Response from MOSIP Registration Client
        """
        try:
            registration_data = {
                "id": "mosip.registration.packet.create",
                "version": "1.0",
                "requesttime": datetime.utcnow().isoformat(),
                "request": {
                    "preRegistrationId": pre_registration_id,
                    "registrationId": None,  # Will be generated
                    "demographicDetails": {
                        "name": extracted_data.get("name", ""),
                        "dateOfBirth": extracted_data.get("dob", ""),
                        "gender": extracted_data.get("gender", ""),
                        "address": {
                            "line1": extracted_data.get("address", ""),
                            "city": extracted_data.get("city", ""),
                            "state": extracted_data.get("state", ""),
                            "postalCode": extracted_data.get("pin_code", "")
                        },
                        "phone": extracted_data.get("phone", ""),
                        "email": extracted_data.get("email", "")
                    },
                    "biometricDetails": biometric_data or {}
                }
            }
            
            if self.registration_client_url:
                response = requests.post(
                    f"{self.registration_client_url}/registration",
                    json=registration_data,
                    headers=self.headers,
                    timeout=30
                )
                if response.status_code == 200:
                    logger.info("Successfully submitted to MOSIP Registration Client")
                    return response.json()
                else:
                    logger.warning(f"MOSIP Registration Client returned status {response.status_code}")
                    return {"status": "error", "message": response.text}
            else:
                # Mock response for demo
                logger.info("MOSIP Registration Client URL not configured, returning mock response")
                return {
                    "id": "mosip.registration.packet.create",
                    "version": "1.0",
                    "responsetime": datetime.utcnow().isoformat(),
                    "response": {
                        "registrationId": f"REG-{datetime.now().strftime('%Y%m%d%H%M%S')}",
                        "status": "SUBMITTED",
                        "message": "Registration submitted successfully (MOCK)"
                    }
                }
        
        except requests.exceptions.RequestException as e:
            logger.error(f"Error connecting to MOSIP Registration Client: {e}")
            return {"status": "error", "message": str(e)}
        except Exception as e:
            logger.error(f"Error in MOSIP Registration submission: {e}")
            return {"status": "error", "message": str(e)}
    
    def get_registration_status(self, registration_id: str) -> Dict:
        """
        Get registration status from MOSIP
        
        Args:
            registration_id: Registration ID to check
        
        Returns:
            Registration status information
        """
        try:
            if self.registration_client_url:
                response = requests.get(
                    f"{self.registration_client_url}/registration/{registration_id}/status",
                    headers=self.headers,
                    timeout=30
                )
                if response.status_code == 200:
                    return response.json()
                else:
                    return {"status": "error", "message": response.text}
            else:
                # Mock response
                return {
                    "id": "mosip.registration.status",
                    "version": "1.0",
                    "responsetime": datetime.utcnow().isoformat(),
                    "response": {
                        "registrationId": registration_id,
                        "status": "PROCESSING",
                        "message": "Registration is being processed (MOCK)"
                    }
                }
        
        except Exception as e:
            logger.error(f"Error getting registration status: {e}")
            return {"status": "error", "message": str(e)}


# Global MOSIP integration instance
mosip_integration: Optional[MOSIPIntegration] = None


def get_mosip_integration() -> MOSIPIntegration:
    """Get or create MOSIP integration instance"""
    global mosip_integration
    if mosip_integration is None:
        import os
        pre_reg_url = os.getenv("MOSIP_PRE_REGISTRATION_URL")
        reg_client_url = os.getenv("MOSIP_REGISTRATION_CLIENT_URL")
        api_key = os.getenv("MOSIP_API_KEY")
        mosip_integration = MOSIPIntegration(
            pre_registration_url=pre_reg_url,
            registration_client_url=reg_client_url,
            api_key=api_key
        )
    return mosip_integration

